name: Flask from Rust

on:
  push

jobs:
  flask-from-rust:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install Flask

    - name: Test run flask
      run: cargo run

    # - name: Flask from Rust
    #   run: |
    #     cargo run &
    #     sleep 7

    # - name: Test API Endpoint
    #   run: curl http://localhost:5000/say_hello
