name: Flask from Rust

on:
  push

jobs:
  flask-from-rust:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install Flask

    - name: Flask from Rust
      run: |
        cargo run &
        sleep 13

    - name: Test API Endpoint
      run: curl http://localhost:5000/say_hello
